version: '3'
services:
  redis:
    container_name: picture
    image: redis
    ports:
      - 6379:6379

  mysql5.7:
    build: ./doc/mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql


  zoo1:
    image: zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    # environment:
      # ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=127.0.0.1:2888:3888;21

  # zoo2:
  #   image: zookeeper:3.6.4
  #   restart: always
  #   hostname: zoo2
  #   ports:
  #     - 2182:2181
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  # zoo3:
  #   image: zookeeper:3.6.4
  #   restart: always
  #   hostname: zoo3A
  #   ports:
  #     - 2183:2181
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181     