
server:
  port: 8800

spring:
  application:
    name: provider-app
  data:
    redis:
      database: 0
      port: 6379
      host: 127.0.0.1
      jedis:
        pool:
          max-idle: 6    #最大空闲数
          max-active: 10 #最大连接数
          min-idle: 2    #最小空闲数
      timeout: 2000   #连接超时
  master:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/picture
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/picture
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  protocol:
   name: dubbo
#    name: tri
#    port: -1
  registry:
    address: zookeeper://localhost:2181
    timeout: 5000000
    # 新加的参数
    parameters:
      blockUntilConnectedWait: 9999999


# application.yml
# application.yml
logging:
  level:
    org.bamboo.mapper: debug







